### ISSUE TITLE
extention dosn't work for me on lazyvim

### ISSUE THREAD

**Issue by mk990** [ccaglak/namespace.nvim#3]
i add it to lazyvim in this dir `lua/plugin/namespace.lua`

```lua
return {
    {
        "ccaglak/namespace.nvim",
        keys = {
            { "<leader>la", "<cmd>GetClasses<cr>", desc = "Get Classes" },
            { "<leader>lc", "<cmd>GetClass<cr>", desc = "Get Class" },
            { "<leader>ls", "<cmd>AsClass<cr>", desc = "As Class" },
            { "<leader>ln", "<cmd>Namespace<cr>", desc = "Namespace" },
        },
        dependencies = {
            "nvim-lua/plenary.nvim",
        },
    },
}
```
i can get commands but its not working

**Comment by ccaglak** [comment]
Hi mk990,
you must have ripgrep installed and php json treesitters parsers.
if everything checks. Whats your operating system?

**Comment by ccaglak** [comment]
> i add it to lazyvim in this dir `lua/plugin/namespace.lua`
> 
> ```lua
> return {
>     {
>         "ccaglak/namespace.nvim",
>         keys = {
>             { "<leader>la", "<cmd>GetClasses<cr>", desc = "Get Classes" },
>             { "<leader>lc", "<cmd>GetClass<cr>", desc = "Get Class" },
>             { "<leader>ls", "<cmd>AsClass<cr>", desc = "As Class" },
>             { "<leader>ln", "<cmd>Namespace<cr>", desc = "Namespace" },
>         },
>         dependencies = {
>             "nvim-lua/plenary.nvim",
>         },
>     },
> }
> ```
> 
> i can get commands but its not working

Hi mk990,
I have tested on lazyvim and it works on mac. 
you must have ripgrep installed and php json treesitters parsers.
if everything checks. Whats your operating system?

**Comment by mk990** [comment]
i use linux also i installed ripgrep , php json in treesitters 
any way to check log file or debug ??

**Comment by ccaglak** [comment]
i will look into it, i just updated package check it out it might have fixed the issue

**Comment by mk990** [comment]
tnx for update 
now i have this error 
```
Failed to source `/home/user/.local/share/nvim/lazy/namespace.nvim/plugin/namespace.lua`

vim/_editor.lua:0: nvim_exec2()../home/user/.local/share/nvim/lazy/namespace.nvim/plugin/namespace.lua: Vim(source):E5113: Error while calling lua chunk: vim/loader.lua:0: ...re/nvim/lazy/namespace.nvim/lua/namespace/getClasses.lua:37: unexpected symbol near '<'
stack traceback:
	[C]: in function 'error'
	vim/loader.lua: in function <vim/loader.lua:0>
	[C]: in function 'require'
	.../.local/share/nvim/lazy/namespace.nvim/lua/namespace.lua:3: in main chunk
	[C]: in function 'require'
	...ocal/share/nvim/lazy/namespace.nvim/plugin/namespace.lua:2: in main chunk
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:481: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480>
	[C]: in function 'xpcall'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480: in function 'source'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:439: in function 'source_runtime'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:407: in function 'packadd'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:342: in function '_load'
	...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:187: in function 'load'
	...share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:117: in function <...share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/keys.lua:107>

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
```

**Comment by ccaglak** [comment]
i apoligize, i messed it up. everything is good now. i will run a virtual machine to see how it works on linux tomorrow

**Comment by mk990** [comment]
yes i see that but its not working in linux any way to debug it?

**Comment by ccaglak** [comment]
getClass.lua is the main file 

```
_G.dd = function(...)
    local obj = select("#", ...) == 1 and select(1, ...) or { ... }
    local s = type(obj) == "string" and obj or vim.inspect(obj)
    if vim.in_fast_event() then
        vim.schedule(function()
            print(s)
        end)
    else
        print(s)
    end
end
```

make sure you have .git or composer.json vendor in your project root
check the values

**Comment by ccaglak** [comment]
which distro do you use

**Comment by mk990** [comment]
archlinux

**Comment by ccaglak** [comment]
tomorrow around this time it will be fixed. thanks

**Comment by mk990** [comment]
thank you

**Comment by ccaglak** [comment]
update it, and try again

**Comment by mk990** [comment]
no not working

**Comment by ccaglak** [comment]
i've found one bug in namespace generater but everything else was working just fine. 
my virtualmachine was arch 24.01 tested on both neovim 9-10 with lazyvim conf.

**Comment by ccaglak** [comment]
[arch-screen0.webm](https://github.com/ccaglak/namespace.nvim/assets/98365888/43430d28-a2ab-4217-9dbc-db648346fd7f)

**Comment by mk990** [comment]
no i update and it not working it something wrong with my config
```lua
return {
    {
        "ccaglak/namespace.nvim",
        keys = {
            { "<leader>la", "<cmd>GetClasses<cr>", desc = "Get Classes" },
            { "<leader>lc", "<cmd>GetClass<cr>", desc = "Get Class" },
            { "<leader>ls", "<cmd>AsClass<cr>", desc = "As Class" },
            { "<leader>ln", "<cmd>Namespace<cr>", desc = "Namespace" },
        },
        dependencies = {
            "nvim-lua/plenary.nvim",
        },
    },
}
```
