### ISSUE TITLE
E492: Not an Editor Command for GetClass and others

### ISSUE THREAD

**Issue by khumam** [ccaglak/namespace.nvim#5]
Hi
I was looking for the PHP auto import namespace and I found this repo. And I think this repo has potential for the future.
Already setup and installed the plugins, but I got this error when access the shortcut or the command

`E492: Not an Editor Command for GetClass` and other commands

Here is my configuration

lua/plugins/phpnamespace.lua

```
return {
    'ccaglak/namespace.nvim',
    keys = {
        { "<leader>la", ":GetClasses<cr>"},
        { "<leader>lc", ":GetClass<cr>"},
        { "<leader>ls", ":ClassAs<cr>"},
        { "<leader>ln", ":Namespace<cr>"},
    },
    dependencies = {
        "nvim-lua/plenary.nvim"
    }
}

```

also I set the keymap

```
    vim.keymap.set("n", "<leader>la", ":GetClasses<cr>")
    vim.keymap.set("n", "<leader>lc", ":GetClass<cr>")
    vim.keymap.set("n", "<leader>ls", ":ClassAs<cr>")
    vim.keymap.set("n", "<leader>ln", ":Namespace<cr>")
```

My machine: 
- LazyVim
- Mac M1
- Planery.vim installed
- PHP and JSON parser installed
- Treesitter installed
- Ripgrep also installed

Thank you for the great plugin mate!

**Comment by ccaglak** [comment]
Hi Khoerul, there was a similar issue in the past with lazyvim config, however i couldn't replicate the issue. i have tried again with no luck, as of right now i could only suggest following with neovim 10, let me know if it works.
also if you share your setup i could test it. thanks
```
return {
    ft = { 'php' },
    'ccaglak/namespace.nvim',
    keys = {
        { '<leader>cc', '<cmd>lua require("namespace.getClass").get()<cr>',   { desc = 'GetClass' } },
        { '<leader>ca', '<cmd>lua require("namespace.getClasses").get()<cr>', { desc = 'GetClasses' } },
    },
   dependencies = {
        "nvim-lua/plenary.nvim"
    }
}
```

**Comment by khumam** [comment]
Hi @ccaglak it solved the problem. Thanks
