### ISSUE TITLE
Doesn't respect composer's psr-4 settings

### ISSUE THREAD

**Issue by Tomsgu** [ccaglak/namespace.nvim#7]
Hi,

With a composer setup:
```json
    "autoload": {
        "psr-4": {
            "App\\": "src/",
            "Other\\SomeBundle\\": "lib/SomeBundle/src/"
        }
    }
```
I end up with following when adding namespace to a class: 
```php
namespace Lib\SomeBundle\Src\Entity;
```

Is there any simple way, how to correctly use custom psr-4 namespaces?

Btw. awesome plugin

**Comment by ccaglak** [comment]
i will have a look at it

**Comment by ccaglak** [comment]
try out branch v2 if your on nightly. its a rewrite
